---
stages:
  - build
  - deploy

variables:
  IMAGE_DEV: ${CI_PROJECT_PATH}_final:$CI_COMMIT_SHA

build:
  stage: build
  tags:
    - as-docker-build
  before_script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - apk add bash && rm -rf /var/cache/apk/*
    - mkdir -pm 700 ~/.ssh
    - eval $(ssh-agent -s)
    - cat $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
  script:
    - >
      bash build.sh
      --compress
      --image-name $IMAGE_DEV

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  tags:
    - as-docker-build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag $IMAGE_DEV $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
